FROM microsoft/azure-cli:latest

LABEL "name"="Azure Cli"
LABEL "maintainer"="strebeld@gmail.com"
LABEL "version"="0.9"
LABEL "com.github.actions.icon"="terminal"
LABEL "com.github.actions.color"="black"
LABEL "com.github.actions.name"="azure-cli"
LABEL "com.github.actions.description"="Runs Azure-Cli"